### ISSUE TITLE
mod_location throws a runtime error

### ISSUE THREAD

**Issue by Tonie-NG** [kaf-lamed-beyt/ng-tech-events#67]
`mod_location` variable (probably just the declaration syntax) throws an "Unhandled Runtime Error"

1. Setup the application on your local machine and start the server on you local machine
2. Click on one of the categories and you'll be met with the error

**Expected behavior**
This shouldn't happen. It's just an unhandled eventuality

**Screenshots**
![error for mod_location](https://github.com/kaf-lamed-beyt/ng-tech-events/assets/81086586/1a8ae9ba-c262-49b9-b383-fac5609d8d93)

**Comment by Tonie-NG** [comment]
I already have a fix for this issue, didn't want to ship it out with my last PR without filing it as an issue. @kaf-lamed-beyt just let me know if I should proceed with the implementation. I basically plan to abstract the functionality into a separate function which will be private for now (only accessible within the file), if we find other usecases then we can probably create a module for it.

**Comment by kaf-lamed-beyt** [comment]
Thanks for reporting this. Can you try adding a `?` before includes? 

It's probably because the variable is undefined at first. Could be as a result of network too, not absolutely sure about that. Last time I ran it locally, everything worked fine.

Lemme know what happens when you add `?`, then we can proceed 🤲🏽
